### ISSUE TITLE
NavBar UI

### ISSUE THREAD

**Issue by josemlegal** [josemlegal/landing-page-estimation#2]

**Comment by josemlegal** [comment]
### Overall description

In this issue, we want to style the NavBar component and then work individually with each one of them in others issues.

### Tasks

- [ ] Add the NavBar component. `0.25`
- [ ] Add company logo.  `0.30`
- [ ] Add 4 tags [Shoes, Clothes, Skate, Basket] to redirect to the desire section of the e-commerce. `0.30`
- [ ] Add the search input. `0.5`
- [ ] Add the "My Account" button, this button should redirect the user to his/her user profile. `0.5`
- [ ] Add "My Cart" icon button, this button should open a dialog of the list of selected products by the user. `1`


![Image](https://github.com/josemlegal/landing-page-estimation/assets/96390036/e52c35f9-8803-4454-a62d-6e00b5a5ca49)



This is the design of this view--> https://www.figma.com/file/woADio6cGZBR6eJTg0TtKo/Untitled?type=design&node-id=0-1&t=Nnarj5e5c3AKLf1q-0

Here you can check the components that we will be using in this project --> https://tailwindui.com/components (If you dont have the credentials you can contact @josemlegal)
